### ISSUE TITLE
Demo projects

### ISSUE THREAD

**Issue by andrey-poltavskiy** [ButchersBoy/MaterialDesignInXamlToolkit#114]
Not compiled in Visual Studio 2013.

**Comment by ButchersBoy** [comment]
Hi, please see:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/31

and 

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/90

**Comment by andrey-poltavskiy** [comment]
Branch net40:
public ICommand RunDialogCommand => new AnotherCommandImplementation(ExecuteRunDialog);

Error	13	; expected	D:\Develop\Tests\MaterialDesignInXamlToolkit\MaterialDesignInXamlToolkit.N4\MainDemo.Wpf\Domain\DialogsViewModel.cs	14	42	MainDemo.Wpf

**Comment by andrey-poltavskiy** [comment]
The problem in using C#6.

**Comment by cH40z-Lord** [comment]
And how is the release date of an IDE related to the status and stability of the language and compiler infrastructure? Keep in mind that you can also use OmniSharp-based tools and editors to compile C# 6 projects since they're using the same compiler (Roslyn) as Visual Studio does.

**Comment by andrey-poltavskiy** [comment]
The companies are not going as fast software updates.
Now hawe problem. From NuGate last assembly "MaterialDesignThemes.Wpf.dll, v1.1.0.234", and DialogClosingEventArgs dont have property "public DialogSession Session { get; }"

**Comment by cH40z-Lord** [comment]
Well, you can still install Visual Studio 2015 Community Edition or use any other OmniSharp-based tool, like I mentioned already. This will fix all of your problems in no time without having to rewrite the entire code-base. Keep in mind that C# 6 is here to stay, it won't go away and the amount of problems you're experiencing will greatly improve with every single month where developers make use of the new features of C# 6

**Comment by ButchersBoy** [comment]
@andrey-poltavskiy also please note you *can* use in a VS2012 project,  you just can't  compile the source.  You can pull in from nuget and begin using without issue.  DialgSession is currently in pre release build, so you have to include pre release versions in nuget search

**Comment by SuicSoft** [comment]
@andrey-poltavskiy Also you can install the Microsoft.Net.Compilers NuGet package, I use this method with VS2013 and it works although the IntelliSense reports errors (because it doesn't understand C#6), but the project builds correctly. If you have any build errors they will appear in the build output. To install it , open the visual studio project , then click Tools > NuGet Package Manager > Package Manager Console. Once loaded change default project (top of package manager console toolbox). And type 

```
Install-Package Microsoft.Net.Compilers
```  
and press enter.

You should have c# 6 working by now. You will have to repeat this for each project you need c#6
