### ISSUE TITLE
Calling  eventArgs.Session.Close(false) directly => InvalidOperationException

### ISSUE THREAD

**Issue by guillaumejay** [ButchersBoy/MaterialDesignInXamlToolkit#156]
Calling             eventArgs.Session.Close(false) directly  throws an invalidOperationException("Dialog session has ended.") (from DialogSession/Close().

Easy to reproduce : MainDemo.Wpf/ DialogsViewModel.cs / ExtendedClosingEventHandler
remove Task.Delay to call eventArgs.Session.Close(false) directly.

**Comment by ButchersBoy** [comment]
OK, yeah makes sense now; I didn't have the code in front of me when we were talking on gitter.

Even though ```eventArgs.Cancel()``` is called the stack has to unwind for the linrary to accept the cancel.  So you can't close inside your ```DialogClosingEventHandler```...which is good because you could find yourself in a nasty loop.

Typically, if you cancel the close, you'll then go into some other kind of wait, be it waiting for the user or a task, so this should be OK.

**Comment by guillaumejay** [comment]
Effectively, I tried this when I was trying to make it work using various test scenarios. In a real program, it's hard to imagine a real case.
