### ISSUE TITLE
Add common button styles for RepeatButton

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#244]
[RepeatButton](https://msdn.microsoft.com/en-us/library/system.windows.controls.primitives.repeatbutton(v=vs.110).aspx) derives from `ButtonBase` but all the current button styles are for controls of type `Button`. 

Is it possible to convert  current styles to use `ButtonBase` or is it necessary to create a similar set of styles for the `RepeatButton`?

**Comment by mgnslndh** [comment]
Any chance of seeing this in 1.5 @ButchersBoy?

**Comment by ButchersBoy** [comment]
Yes...1.5._1_ :wink: 

Seriously, I was just looking at your other request for the multi button thingy, and considering what to do.  I might push 1.5.0 out sooner rather than letter, get the transitions in the wild, and then concentrate on some of these smaller things for 1.5.1> 1.5.*....think I need a period of consolidation for clearing these issues and smaller requirements up - backlog is growing...

I want to keep the release rolling at a reasonable tempo, which really means getting transitions out there so I can start tidying other bits-and-bobs a bit.

**Comment by ButchersBoy** [comment]
FYI: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/milestones

**Comment by mgnslndh** [comment]
Super nice! Thanks! I made a simple test of changing the raised button style to use ButtonBase instead of Button and it seemed to work fine for a RepeatButton
