### ISSUE TITLE
Create toolbox items

### ISSUE THREAD

**Issue by itechy21** [ButchersBoy/MaterialDesignInXamlToolkit#26]
As the title says would it be possible to add toolbox items for all the controls?

**Comment by itechy21** [comment]
Just realised how derpy this is. Closing...

**Comment by ButchersBoy** [comment]
Cool, no problem :-)

**Comment by jamespfluger** [comment]
Maybe a crazy question, but which DLLs are supposed to add the controls? I can add `MaterialDesignThemes.Wpf.dll` just fine, but that doesn't include controls such as buttons, grids, and trees. It's also odd that I can add that without adding the dependency `MaterialDesignColors.dll` which has no dependencies.

Because of this, I can't add MahMetro material design variant, despite being able to use MahMetro by itself after adding its own ControlzEx dependency.

Which `dll` files do I need to add and in what order? I'm using .NET 4.5 for my project and am adding the 4.5 `dll`s to my toolbox as well.
