### ISSUE TITLE
calendar does not support RTL langauge

### ISSUE THREAD

**Issue by nadavten** [ButchersBoy/MaterialDesignInXamlToolkit#288]

**Comment by jdf3** [comment]
Hi nadavten,

Please forgive my ignorance, as I'm learning about the nuances of RTL UI on-the-fly here.

I think all you should need to do is set `FlowDirection="RightToLeft"` somewhere in the logical tree, since just having the `CurrentUICulture` be a RTL language doesn't actually orient things for you this way in WPF.

Before:
![image](https://cloud.githubusercontent.com/assets/838256/13848992/363277d4-ec22-11e5-83ec-2a529ca038b5.png)

After:
![image](https://cloud.githubusercontent.com/assets/838256/13848963/151b825c-ec22-11e5-904e-ff1daa89f405.png)

Is this what you were looking for, or is there another problem that I haven't addressed here?

**Comment by ButchersBoy** [comment]
@hshahdoost anything to add on this?

**Comment by nadavten** [comment]
How did u get the hebrew to show?

**Comment by jdf3** [comment]
@nadavten Set the `FrameworkElement.Language` property of your control, or apply the `xml:lang` attribute to the XAML of your control.

**Comment by nadavten** [comment]
I did set xml:lang="he-IL" and its not doing the job

**Comment by jdf3** [comment]
OK, I see the problem.  Doing either of the approaches I suggested won't work for now.  If you set the `CurrentUICulture` to `he-IL`, things should work - that's how I got the picture before.

**Comment by nadavten** [comment]
where and how do i set this ?

**Comment by nadavten** [comment]
thank you very much !

**Comment by hshahdoost** [comment]
@ButchersBoy I'm sorry it took so long to answer, I haven't worked on the calendar since persian calendar follows a totally different story. but if it's required I can make the calendar right to left as well.
