### ISSUE TITLE
Dialogs in dark theme

### ISSUE THREAD

**Issue by negue** [ButchersBoy/MaterialDesignInXamlToolkit#377]
I don't know if this is a bug, but if you change the Theme to Dark and open a dialo, it will be shown in the Light-Theme. 

Is this by-design?

**Comment by ButchersBoy** [comment]
Yes, this is actually by design.  Last time I checked there were no recommendations for dark dialogs on Google's specs, and certainly most apps on my Android phone have light dialogs, even if the are using a dark theme.  Plus, I think lighter dialogs provide better consistency and looks, even in a dark theme.

However, you should be able to override it by bringing in the dark resource dictionary into your content.
