### ISSUE TITLE
Search bar...

### ISSUE THREAD

**Issue by n3R0d0T** [ButchersBoy/MaterialDesignInXamlToolkit#38]
Adding a search bar would be nice, or at least give me a permission to make one..

**Comment by ButchersBoy** [comment]
Like this one?

http://img.wonderhowto.com/img/original/69/30/63539474840462/0/635394748404626930.jpg

**Comment by ButchersBoy** [comment]
OK, rather than building a specific search control I've added a new control "ColorZone" which provides a more flexible way to construct your UI, whilst sticking within your palette.  In the demo app I've illustrated how you could use this to build a search bar...happy to hear any feedback.  Got some more extra button styles coming too to help.

![image](https://cloud.githubusercontent.com/assets/658107/9628694/d162adb8-5164-11e5-9e1d-9ca053e55d5e.png)
