### ISSUE TITLE
Expander does not work as expected with a ScrollViewer inside

### ISSUE THREAD

**Issue by mrfrostfire** [ButchersBoy/MaterialDesignInXamlToolkit#415]
As the Expander template puts the content inside a stackpanel, it breaks the functionality of ScrollViewer. StackPanel does not take height/width constraints into consideration and thereby the content will overflow and the scrollviewer not show its scrollbars properly.

**Comment by ButchersBoy** [comment]
Expander template has been largely changed.  Feel free to re-open if still an issue.

**Comment by Maradaehne** [comment]
Hi,

I still got this issue. I did a quick and dirty example project which reproduce the issue.
https://github.com/Maradaehne/ScrollviewerTest

With MaterialDesignInXamlToolkit the expander will not display the scrollbar if content exceeds the window height. When MaterialDesignInXamlToolkit  is not used the scrollbar will be displayed as desired. I guess the issue is caused by the StackPanel as mrfrostfire mentioned.

Can you suggest a workaround for this?
