### ISSUE TITLE
Dialog loses focus in subsequent messages

### ISSUE THREAD

**Issue by stealthcold** [ButchersBoy/MaterialDesignInXamlToolkit#445]
Hello,

I have a Dialog that loses focus when I execute some threaded methods.
1. First, I show a message to the user (works well);
2. Then, it starts another dialog with a progress ring (works well);
3. At the end, if we have a error response from server, another dialog pops-out with the error message. As you can see here:

![example](https://cloud.githubusercontent.com/assets/836311/16803977/be29f2a6-48df-11e6-8efe-4790bcc38ead.gif)

The problem is: the "OK" button is disabled in the last Dialog. And just receive focus when I click it once.

Here is a source code: https://drive.google.com/open?id=0B7dlCQ9y_LsDdm1mU2RNNzlXem8

I'm doing it wrong or is it a bug?

**Comment by ButchersBoy** [comment]
It's a current known bug.

**Comment by stealthcold** [comment]
And there is any workaround?

**Comment by ButchersBoy** [comment]
Well, until the fix I guess you could manually set focus to one of your controls just after it loads.

**Comment by stealthcold** [comment]
Okay, I'll try. Thanks!

**Comment by HitomiTenshi** [comment]
This bug only seems to come up after the background is dimmed.

I have a similar scenario, where I show a ProgressDialog before showing an ErrorDialog. If the operation in the background completes very quickly, the background dimmer on the ProgressDialog doesn't get loaded and the ErrorDialog after that doesn't have this focus bug.

**Comment by ButchersBoy** [comment]
Yeah, I'm aware, I have same issue in my own projects, I 'll hopefully get to it soon.

James

**Comment by rgiosa** [comment]
Hello! Does anyone have a solution to this issue?

**Comment by maciz84** [comment]
This issue is very frustrating. I have noticed in general that databinding commands or visibility states of controls in a dialog content are very buggy. I am trying to use less of this which is making life difficult for me the materialdialog host and it's dialog content stuff is key to everything about this library.

**Comment by maciz84** [comment]
What I have picked up on is that if you are using MVVM and have lots of dialog hosts all over the place with bindings to a view model you will certainly  run into this problem.

**Comment by ButchersBoy** [comment]
OK, I will look at this as my next priority.  If anyone has any more sample repos to help me diagnose and test this then _please_ post them.

**Comment by maciz84** [comment]
Hi James,

Thanks for looking into this? The thing is that it is so sporadic/intermitent it is so damn hard to figure out what is causing this. I will keep trying to test and if I find a common thread I will post a repo.

**Comment by ButchersBoy** [comment]
@stealthcold can you post your initial attachment as a GitHub repo?

**Comment by ButchersBoy** [comment]
I need things to work with and I need them in GitHub repos...

**Comment by stealthcold** [comment]
Hi @ButchersBoy , here it go:

https://github.com/stealthcold/dialoghostexample.git

**Comment by ButchersBoy** [comment]
Build 2.2.0-ci743 fixes @stealthcold issue.

Possibly other people's as well; but I don't know.  Please retest and report back.

**Comment by stealthcold** [comment]
Well, I've tested and didn't see the problem anymore.

**Comment by ButchersBoy** [comment]
One down.  :)   I'll wait to see what @maciz84 comes back with before closing the issue.

**Comment by HitomiTenshi** [comment]
It does solve the "visual" problem somewhat, I still see the gray overlay for a split second on @stealthcold 's example.

It doesn't solve the focus issue though. I have forked @stealthcold 's project and added a `IsDefault="True"` to all necessary buttons.

https://github.com/HitomiTenshi/dialoghostexample.git

What's supposed to happen:

1. Start debug
2. Press Enter
3. Dialog pops up
4. Press Enter
5. Yes Button get's triggered, because of its `IsDefault="True"` setting
6. Loading screen pops up
7. **After some time:** Message Dialog gets set
8. Press Enter
9. Dialog closes, because the Close Button gets triggered
10. I now should be back at the beginning and pressing Enter again should restart this example dialog loop

What actually happens:

1. Scenario 1
1.1. Start debug
1.2. Press Enter
1.3. Dialog pops up -> **Loses focus here**
1.4. Press Enter -> _Focus lost, nothing happens_
2. Scenario 2
2.1. Start debug
2.2. Press Enter
2.3. Dialog pops up
2.4. Click on the No Button -> **DialogHost object eats up focus now**
2.5. Dialog closes
2.6. Press Enter -> _Nothing happens, it should trigger the Button on the main window but focus is somehow lost somewhere inside the DialogHost_
2.6.1. Clicking on the Window background doesn't help, pressing Enter won't do anything now.

Weird things:

If I do not press Enter on the window, but instead click on the

"Button" Button

and then on the

"No" Button

Focus is being kept on the Main Window and pressing enter actually will trigger the "Button" button.

**Comment by ButchersBoy** [comment]
@HitomiTenshi thanks for this analysis, very helpful.

**Comment by maciz84** [comment]
Hi Guys,

I was away this afternoon.Started testing will let you know soon of findings

**Comment by maciz84** [comment]
Hi Guys,

Mine seems to be working now:) Thanks James

**Comment by nazgul87** [comment]
Hi @ButchersBoy, I've been using those controls and they're really amazing.
About Dialog specifically I have some questions and I want to know if you could help me.
I'm developing an application using MVVM pattern. If we are very stricted with this pattern, I think we shouldn't use Dialog within the viewmodel because we are breaking the decoupling between view and viewmodel , specially creating views from viewmodel. Please, correct me if I'm wrong .

I'm trying to achieve the behavior @stealthcold is describing (show one dialog after hide the first one) but showing/hiding dialogs with viewmodel commands. Is this possible?

I'm thinking in something like dependency injection service, but I don't know how to take DialogSession without create an event handler.

I'll appreciate your comments.

thanks in advance.

**Comment by ButchersBoy** [comment]
Firstly, things might depend on if you are in a multi window environment.  If you only have a single window, things get easier, so I'll talk about that scenario.

Lets assume you have a single ```DialogHost``` in a window, and in your strict MVVM scenario you want to inject an interface into you view model that allows you to show a dialog.  Obviously you need to get hold of the ```DialogHost``` to be able to start a dialog.

The easiest way to do it is create a class that is aware of your Window.  This will be the *only* class in your app which can associate a dialog with a Window.  Create an interface and implementaion to wrap the Window extension methods in this class:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/31e0dc6b586595276fa9237f934520089913be8b/MaterialDesignThemes.Wpf/DialogHostEx.cs#L80

So your interface might look like
```
IDialogShowerThingy
    async Task<object> ShowDialog(object content, DialogOpenedEventHandler openedEventHandler, DialogClosingEventHandler closingEventHandler)
```

The impl a bit like:
```
public async Task<object> ShowDialog(object content, DialogOpenedEventHandler openedEventHandler, DialogClosingEventHandler closingEventHandler)
{
    //call the extension method
    _myAppWindow.ShowDialog(content, openedEventHandler, closingEventHandler);
}
```

Then, you can pass your ```IDialogShowerThingy``` into your view model, which will now be blissfully unaware of the Window itself.

**Comment by nazgul87** [comment]
Hi James, sorry for my late answer.

I was working on the idea you said and I finally get show dialog from ViewModel (in the scenario I had on mind). That's exactly that I need :). 

Thank you so much for the help.

P.S. your material Design toolkit is amazing.
