### ISSUE TITLE
ComboxPopUp DefaultTemplate not correct

### ISSUE THREAD

**Issue by elvince** [ButchersBoy/MaterialDesignInXamlToolkit#552]
Hi,

In your demo project, if you remove the margin "16" in the MainWindow and also in TextFields, then you add a new row in the grid, then add
`<ComboBox Grid.Row="20" Grid.Column="0"  Grid.ColumnSpan="10" materialDesign:HintAssist.Hint="OS">
                <ComboBoxItem>Andoid</ComboBoxItem>
                <ComboBoxItem>iOS</ComboBoxItem>
                <ComboBoxItem>Linux</ComboBoxItem>
                <ComboBoxItem>Windows</ComboBoxItem>
            </ComboBox>`

Launch it full screen and you will see that the combo box is not drawn properly.
In fact, the SelectedItem is not inside the "comboxpopup header". So you think that this element is not belonging to the popup.

![capture](https://cloud.githubusercontent.com/assets/7021898/20307112/3455c994-ab3e-11e6-92f2-178889b6c6ac.PNG)

I hope you can fix this template.

Thanks,

**Comment by l1pton17** [comment]
When combobox doesn't have enough space to show suggestion list right under the selecteditem, it shows list out like standard combobox do.
Maybe the solution of this problem is to somehow mark the selecteditem that this list belongs to it or show selecteditem in the suggestion list when it stands out.
Also, you can use ComboBoxAssist.ShowSelectedItem in order to show selecteditem in the drop down list.

**Comment by ButchersBoy** [comment]
@l1pton17 I think if we have to display in "classic Windows" mode we should probably do the ShowSelectedItem==true behaviour by default.

**Comment by l1pton17** [comment]
@ButchersBoy yeah, i thought about it when i was typing previous message :smile:

**Comment by elvince** [comment]
Excellent Thanks!
