### ISSUE TITLE
Multiple DialogHost problem

### ISSUE THREAD

**Issue by stealthcold** [ButchersBoy/MaterialDesignInXamlToolkit#621]
Hi!

I'm developing an application with multiple DialogHosts.
When I close a new view (which has a DialogHost) it takes some time to call the unload event from the DialogHost class and remove that view from de LoadedInstances.
And if I try to open that view imediatelly, it shows me this message:

**Multiple viable DialogHosts.  Specify a unique Identifier on each DialogHost, especially where multiple Windows are a concern.**

If I remove the "if (targets.Count > 1)", my application seems to work normally.

Could you take a look?

Here is a repository with a simple example (and how to reproduce the error):
https://github.com/stealthcold/dialoghostexample.git

thanks

**Comment by ButchersBoy** [comment]
Exactly as the error says:

__Multiple viable DialogHosts. Specify a unique Identifier on each DialogHost, especially where multiple Windows are a concern.__

When you first open the dialog it works, because the second dialoghost hasnt loaded yet.  Then, when you reopen there are two loaded dialoghosts, hence __Multiple viable Dialoghosts__.

It doesn't know which one to use.

You can do something like this:

```
<materialDesign:DialogHost Identifier="Main">
```
```
var result = await DialogHost.Show(view, "Main");
```

**Comment by velzher** [comment]
Estas lineas pueden ayudarte:

var Popup = new usercontrolEjemplo() { };
DialogHostEx.ShowDialog(this, Popup);
