### ISSUE TITLE
Adding window background removes background from combobox popup

### ISSUE THREAD

**Issue by gregsdennis** [ButchersBoy/MaterialDesignInXamlToolkit#630]
Given a WPF window containing a ComboBox, the ComboBox popup loses its background when the window has a non-solid background (e.g. LinearGradientBrush).

![croppercapture 1](https://cloud.githubusercontent.com/assets/2676804/23107841/6c783f4c-f769-11e6-90b8-1b0b0d9a0ce1.png)

Solid backgrounds work fine as the ComboBox takes the background color of the window.

I've forked the repo and created [a new solution](https://github.com/gregsdennis/MaterialDesignInXamlToolkit/tree/master/ComboBoxBackgroundIssue) to demonstrate this issue.

**Comment by Keboo** [comment]
The issue is kinda the result of [ComboBoxPopup.SetupBackground](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs#L210) and the default value of the [Background property](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs#L125) and a bit because of how Popups work.

Since the template for the ComboBox is setting [AllowsTransparency to true](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml#L449) on the popup, the rendering of the popup itself will be transparent, and since it never finds a solid color brush in the visual tree, the background of the popup (and consequently everything bound to this property) end up rendering transparent.


IMHO there are a couple potential "fixes" for this:

- Set a default brush on the Background property of ComboBoxPopup.Background. 
- In SetupBackground put in some default brush if one is not found.
- Set a reasonable theme brush on the ComboBoxPopup within the ComboBox control template.

@ButchersBoy any thoughts?

**Comment by gregsdennis** [comment]
Is there any reason why the pop-up has to be a solid brush?  If it's looking for a brush in the visual tree, wouldn't any brush on a "background" property work?

If anything I would have expected to see the gradient in the pop-up.

**Comment by Keboo** [comment]
I suspect there are likely a couple reasons for the solid color brush restriction.

The current template has quite a few things that get bound to this property. You can do a search for `{Binding ElementName=PART_Popup, Path=Background}` in the [combo box template file](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml). If you remove the SolidColorBrush condition, and open the combo box on your example project you will see how many things don't display correctly because the brush is used multiple times on many of the smaller elements not just the popup root.

Granted the above issues with the template could be addressed so that the brush was only applied at the root, but I am not sure that is desirable. 
Specifically looking at the gradient brush like in your example, if that were applied to the root combobox popup it would render the gradient for the size of the combobox popup which will be different than the rendering it did for the size of the window. IMO this looks weird (but I am a dev not a designer), and likely the reason that the default WPF combobox just defaults to a solid color.

**Comment by gregsdennis** [comment]
I agree that the different gradient size would look odd, but IMO that doesn't warrant disallowing it.

Regardless, it seems I may have a workaround by simply creating a derived style for the pop-up that explicitly sets the background.
