### ISSUE TITLE
Dialogs are moved off-center near the edges of screen.

### ISSUE THREAD

**Issue by metherul** [ButchersBoy/MaterialDesignInXamlToolkit#672]
This is an odd issue, I have to admit. 

When the DialogHost's parent is moved to the edges of the screen it becomes off center, moving away from the edge. 

Screenshots:
http://i.imgur.com/IV6ZRgm.png 
http://i.imgur.com/J6qsGMX.png
http://i.imgur.com/wqd8G2l.png

Normal View:
http://i.imgur.com/Pt1iQZj.png

**Comment by Keboo** [comment]
The reason this is occurring is because the dialogs are implemented with the WPF popup control. This control actively tries to position itself onscreen. 
The extra space you see between the edge of the screen and the edge of the dialog is controlled by the DialogHost.DialogMargin property. [The default is 22](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L474).

**Comment by metherul** [comment]
Ah, thanks for clearing it up.

Closed.
