### ISSUE TITLE
SOLVED - Disable button with RelayCommand

### ISSUE THREAD

**Issue by avechuche** [ButchersBoy/MaterialDesignInXamlToolkit#699]
Hello, I do not know if it is a bug, but when I disable a button using RelayCommand(Execute, CanExecute), the functionality is blocked, but the button is still active visually. The type of button I use is "MaterialDesignFloatingActionAccentButton"

`private ICommand _searchCommand;`

```
public ICommand SearchCommand => _searchCommand ??
                                         (_searchCommand = new RelayCommand(Search, CanExecute()));
```

**Comment by Keboo** [comment]
Hi @avechuche the RelayCommand class, is this coming from MVVMLight or some other library?

**Comment by avechuche** [comment]
Hi @Keboo, sorry, yes im use MVVM Light 5.3.0.

**Comment by Keboo** [comment]
@avechuche MVVMLight has two RelayCommand classes in slightly different namespaces. I suspect you are likely using the non-wpf one.
GalaSoft.MvvmLight.Command**Wpf**.RelayCommand
GalaSoft.MvvmLight.Command.RelayCommand

Typically you want to always favor using the WPF one, since it registers up on the [CommandManager.RequerySuggested](https://msdn.microsoft.com/en-us/library/system.windows.input.commandmanager.requerysuggested.aspx) event. If you use the other one, it is up to you to call RelayCommand.RaiseCanExecuteChanged() anytime the conditions inside of your CanExecute method change.

**Comment by avechuche** [comment]
@Keboo I've solved the problem. I always use "GalaSoft.MvvmLight.CommandWpf". I changed my project from .net 4.0 to 4.5 to use MaterialDesign and I had to reinstall mvvmlight and did not notice that I changed the references (GalaSoft.MvvmLight.Command). Thank you for all!
