### ISSUE TITLE
Wrong property "HorizontalContentAlignment" for style 'GridViewColumnHeader' ?

### ISSUE THREAD

**Issue by bibimorlet** [ButchersBoy/MaterialDesignInXamlToolkit#709]
Hi ButchersBoy,
Thanks for your job, it's really helpful to learn Material Design on XAML files.

Working with ListView.Gridview objects, I have seen on the line 80 of MaterialDesignTheme.ListView.xaml that the property HorizontalContentAlignment doesn't work (it does nothing when I change the value of the property), whereas the VerticalContentAlignment works.
`<Style x:Key="{x:Type GridViewColumnHeader}" TargetType="GridViewColumnHeader">`
       `   <Setter Property="HorizontalContentAlignment" Value="Left" />`                     (<== Here)
        `   <Setter Property="VerticalContentAlignment" Value="Center" />`
        `   <Setter Property="TextBlock.FontWeight" Value="Medium" />`
        `   <Setter Property="OverridesDefaultStyle" Value="True" />`
        `   <Setter Property="Padding" Value="{Binding RelativeSource={RelativeSource Self}, Path=(wpf:DataGridAssist.ColumnHeaderPadding)}" />`
        `<   Setter Property="Foreground" Value="{DynamicResource MaterialDesignColumnHeader}"`
[...]
`</Style>`
To change the content's behaviour horizontally, I think we have to use the property "**HorizontalAlignment**", it works for me.

I hope that my request will be useful for people who are working with your toolkit.

**Comment by Keboo** [comment]
Hi @bibimorlet 

You are correct that the HorizontalContentAlignment does not work for aligning the content of the column header. This appears to be a bug.
The [HorizontalContentAlignment is being applied](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListView.xaml#L95) to the HorizontalAlignment of the ContentPresenter that contains the header content. The problem is that the [Border](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListView.xaml#L90) that contains it, is the first child inside of a DockPanel. This means that its Dock property is defaulted to Left making the size of the Border match the size of the content presenter, effectively negating the HorizontalContentAlignment. 
When you set the HorizontalAlignment property on the ColumnHeader, it is actually affecting the layout of the column header, rather than simply letting the content position itself within the column header.

PR #715 fixes this by moving the content to be the last child in the DockPanel. By default the last child of the DockPanel will fill the available space.
