### ISSUE TITLE
Button click issue in PopupBox template

### ISSUE THREAD

**Issue by issam1975** [ButchersBoy/MaterialDesignInXamlToolkit#734]
Hi,
 i have to click twice to get the button inside the template Onclick event fired,
and it happen only if PopupMode="MouseOver" or "MouseOverEeager" not click

        <materialDesign:PopupBox HorizontalAlignment="Center"
                                 PlacementMode="TopAndAlignCentres"
                                 PopupMode="MouseOverEager"
                                 StaysOpen="True">
            <materialDesign:PopupBox.ToggleContent>
                <materialDesign:Badged Badge="2"
                                       x:Name="MainMenuButton"
                                       VerticalAlignment="Stretch"
                                       HorizontalAlignment="Center">
                    <Button Content="{Binding Designation}"
                           Click="Button_Click"
                            Height="50"
                            VerticalAlignment="Stretch" />
                </materialDesign:Badged>
            </materialDesign:PopupBox.ToggleContent>
        </materialDesign:PopupBox>

       private void Button_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("ok");                
        }

**Comment by ButchersBoy** [comment]
Hi, this is not a bug.

The ```.ToggleContent``` is hosted in a ```ToggleButton```.

You are putting a button inside a button.  Which doesn't make any sense.  You should put content other than a button inside a button.  You can use the ```Opened``` or (```ToggleCheckedContentClick```) event to know when the user clicks

**Comment by issam1975** [comment]
hmmm okay,
i want to use the trigger button click for some action, and mouse over to show the popup content .

what are my options : 
- retemplate the control and replace the togglebutton by something else ?
- .....?

**Comment by Keboo** [comment]
A couple thoughts to accomplish what you want.

* Change the [ClickMode](https://msdn.microsoft.com/en-us/library/system.windows.controls.primitives.buttonbase.clickmode(v=vs.110).aspx) on the inner button to Pressed. As @ButchersBoy pointed out, nesting buttons is usually a bad idea because you end up with multiple buttons competing over mouse events and mouse capture.
* Create your own control for this. Though was you want is kinda similar to the PopupBox the behavior you want, is different enough it probably should be its own control. I would suggest copying the PopupBox code and template as a starting point and modify it or simple start with a toggle button and a popup and build the functionality you describe.

**Comment by issam1975** [comment]
well changing the ClickMode to Press did the trick :)

remain just this issue and we are done ;)
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/733
