### ISSUE TITLE
Drawer content opening time

### ISSUE THREAD

**Issue by TimoDik** [ButchersBoy/MaterialDesignInXamlToolkit#877]
Is there any way to change the opening time? For the side menu to be faster/slower

**Comment by Keboo** [comment]
@TimoDik no. At preset these are all fixed in the [DrawerHost template](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L750-L928).

You could simply copy the template into your project (to override the default one), and adjust the timings as you need.

**Comment by TimoDik** [comment]
@Keboo thank you too mach
