### ISSUE TITLE
ContextMenu not updating on theme base change.

### ISSUE THREAD

**Issue by Tide** [ButchersBoy/MaterialDesignInXamlToolkit#915]
I am running in to an issue and am not sure if this is intended or unavoidable.  I am using a context menu and want to be able to change the theme base from light to dark and have the context menu do so as well.

I have created a repository to illustrate the problem.  Simple click show context menu then click toggle theme base.  Then click show context menu again.  The context menu will still be light or dark depending on what the theme base is when the context menu is first opened.  It will not change after that.

https://github.com/Tide/MaterialDesignContextMenu

**Comment by Tide** [comment]
![screenshot 2](https://user-images.githubusercontent.com/237330/37740047-a9f82bfc-2d32-11e8-87d3-77acdf0added.png)

**Comment by Keboo** [comment]
Hi @Tide, yea the context menu can be a tricky thing. First thank you for the sample application, it makes it much easier to track down issues like this.

In your sample application you will notice if you simply right click after changing the theme that the context menu does properly update its theme. So the issue comes with your Show Context Menu button.  The problem is that when showing the context menu by manually by setting the `IsOpen` property you also need to make sure the `PlacementTarget` gets set. With your example the simplest solution is to simply set it right in the Window's constructor.

```C#
MainContextMenu.PlacementTarget = this;
```

**Comment by Tide** [comment]
Man @Keboo you are awesome.  I wish I had posted sooner.  I spent a lot of time trying to get around or figure that out.  Wish that was the first time :).  Your suggestion fixed my issue as you said it would.

Thanks again!
